In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option('display.max_columns', None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [19]:
#Load the Dataset
df = pd.read_csv("login_logs.csv")

In [20]:
# #Display Dataset
# df.head()               #First 5 rows
# df.tail()               #Last 5 rows
# df.sample(5)            #Random 5 rows

In [21]:
print(df.shape)

(30001, 16)

In [22]:
#Check Column Names
df.columns

Index(['index', 'Login Timestamp', 'User ID', 'Round-Trip Time [ms]',
       'IP Address', 'Country', 'Region', 'City', 'ASN', 'User Agent String',
       'Browser Name and Version', 'OS Name and Version', 'Device Type',
       'Login Successful', 'Is Attack IP', 'Is Account Takeover'],
      dtype='str')

In [23]:
#Rename coln
df.columns = [
    "Record_ID",
    "Login_Timestamp",
    "User_ID",
    "Round_Trip_Time_ms",
    "IP_Address",
    "Country_name",
    "Region",
    "City",
    "Autonomous_System_Number_ASN",
    "User_Agent_String",
    "Browser_Name_and_Version",
    "OS_Name_and_Version",
    "Device_Type",
    "Login_Successful",
    "Is_Attack_IP",
    "Is_Account_Takeover"
]
df.head()

,Record_ID,Login_Timestamp,User_ID,Round_Trip_Time_ms,IP_Address,Country_name,Region,City,Autonomous_System_Number_ASN,User_Agent_String,Browser_Name_and_Version,OS_Name_and_Version,Device_Type,Login_Successful,Is_Attack_IP,Is_Account_Takeover
0,0,43:30.8,-4.320000e+18,NaN,10.0.65.171,NO,-,-,29695,Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like ...,Firefox 20.0.0.1618,iOS 13.4,mobile,False,False,False
1,1,43:43.5,-4.320000e+18,NaN,194.87.207.6,AU,-,-,60117,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 46.0.2490,Android 4.1,mobile,False,False,False
2,2,43:55.9,-3.280000e+18,NaN,81.167.144.58,NO,Vestland,Urangsvag,29695,Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) ...,Android 2.3.3.2672,iOS 7.1,mobile,True,False,False
3,3,43:56.2,-4.320000e+18,NaN,170.39.78.152,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile WebView 85.0.4183,Android 4.1,mobile,False,False,False
4,4,43:59.4,-4.620000e+18,NaN,10.0.0.47,US,Virginia,Ashburn,398986,Mozilla/5.0 (Linux; U; Android 2.2) Build/NMA...,Chrome Mobile WebView 85.0.4183,Android 2.2,mobile,False,True,False

In [24]:
#Dataset Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30001 entries, 0 to 30000
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Record_ID                     30001 non-null  int64
 1   Login_Timestamp               30001 non-null  str
 2   User_ID                       30001 non-null  float64
 3   Round_Trip_Time_ms            1462 non-null   float64
 4   IP_Address                    30001 non-null  str
 5   Country_name                  30001 non-null  str
 6   Region                        29968 non-null  str
 7   City                          29996 non-null  str
 8   Autonomous_System_Number_ASN  30001 non-null  int64
 9   User_Agent_String             30001 non-null  str
 10  Browser_Name_and_Version      30001 non-null  str
 11  OS_Name_and_Version           30001 non-null  str
 12  Device_Type                   29999 non-null  str
 13  Login_Successful              30001 non-null  bool
 14  Is_Attack_IP                  30001 non-null  bool
 15  Is_Account_Takeover           30001 non-null  bool
dtypes: bool(3), float64(2), int64(2), str(9)
memory usage: 3.1 MB

In [25]:
#Statistical Summary

# df.describe()

#For all columns:
df.describe(include='all')

,Record_ID,Login_Timestamp,User_ID,Round_Trip_Time_ms,IP_Address,Country_name,Region,City,Autonomous_System_Number_ASN,User_Agent_String,Browser_Name_and_Version,OS_Name_and_Version,Device_Type,Login_Successful,Is_Attack_IP,Is_Account_Takeover
count,30001.000000,30001,3.000100e+04,1462.000000,30001,30001,29968,29996,30001.000000,30001,30001,30001,29999,30001,30001,30001
unique,NaN,20801,NaN,NaN,16136,111,373,1568,NaN,4358,385,151,5,2,2,1
top,NaN,43:55.9,NaN,NaN,10.0.77.228,NO,-,-,NaN,Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) ...,Chrome Mobile WebView 85.0.4183,iOS 11.2.6,mobile,True,False,False
freq,NaN,6,NaN,NaN,96,15516,12612,12502,NaN,3460,5421,5982,20829,15084,27278,30001
mean,15000.000000,NaN,-1.514631e+18,699.446648,NaN,NaN,NaN,NaN,138794.558515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,8660.687049,NaN,4.749304e+18,1209.437790,NaN,NaN,NaN,NaN,163231.716447,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,-9.220000e+18,10.000000,NaN,NaN,NaN,NaN,224.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,7500.000000,NaN,-4.320000e+18,472.000000,NaN,NaN,NaN,NaN,29695.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,15000.000000,NaN,-4.320000e+18,542.000000,NaN,NaN,NaN,NaN,41164.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,22500.000000,NaN,2.080000e+18,694.750000,NaN,NaN,NaN,NaN,207674.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,30000.000000,NaN,9.220000e+18,34284.000000,NaN,NaN,NaN,NaN,507635.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
#Check Missing Values

# df.isnull().sum()


#To calculate the percentage of missing values:
missing = (df.isnull().sum() / len(df)) * 100

missing.sort_values(ascending=False)

Round_Trip_Time_ms              95.126829
Region                           0.109996
City                             0.016666
Device_Type                      0.006666
User_ID                          0.000000
Login_Timestamp                  0.000000
Country_name                     0.000000
Record_ID                        0.000000
IP_Address                       0.000000
Autonomous_System_Number_ASN     0.000000
Browser_Name_and_Version         0.000000
User_Agent_String                0.000000
OS_Name_and_Version              0.000000
Login_Successful                 0.000000
Is_Attack_IP                     0.000000
Is_Account_Takeover              0.000000
dtype: float64

In [27]:
#Check Duplicate Records
df.duplicated().sum()

# If duplicates exist:

df = df.drop_duplicates()

# # Verify:

df.duplicated().sum()

np.int64(0)

In [28]:
#Check Data Types
df.dtypes

Record_ID                         int64
Login_Timestamp                     str
User_ID                         float64
Round_Trip_Time_ms              float64
IP_Address                          str
Country_name                        str
Region                              str
City                                str
Autonomous_System_Number_ASN      int64
User_Agent_String                   str
Browser_Name_and_Version            str
OS_Name_and_Version                 str
Device_Type                         str
Login_Successful                   bool
Is_Attack_IP                       bool
Is_Account_Takeover                bool
dtype: object

In [29]:
# Convert Login Timestamp
df["Login_Timestamp"] = pd.to_datetime(
    df["Login_Timestamp"],
    errors="coerce"                  
)                                              #errors="coerce" converts invalid timestamps into NaT (Not a Time) instead of stopping with an error.

C:\Users\SACHIN\AppData\Local\Temp\ipykernel_29180\2737511482.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Login_Timestamp"] = pd.to_datetime(

In [30]:
df["Login_Timestamp"].isnull().sum()  #This tells you how many invalid timestamps were found.

np.int64(18118)

In [31]:
# df["Login_Timestamp"] = pd.to_timedelta(
#     "00:" + df["Login_Timestamp"]
# )
# df["Login_Timestamp"].head(10)

In [32]:
# #Final Dataset Check
# df.head()
# df.info()
df.shape

(30001, 16)

In [33]:
# Check unique values
for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique()[:10])   # First 10 unique values

# This helps us understand the dataset before analysis.

Record_ID
[0 1 2 3 4 5 6 7 8 9]

Login_Timestamp
<DatetimeArray>
[                'NaT', '2026-08-05 00:01:06', '2026-08-05 00:01:12',
 '2026-08-05 00:02:24', '2026-08-05 00:04:24', '2026-08-05 00:05:54',
 '2026-08-05 00:06:12', '2026-08-05 00:06:54', '2026-08-05 00:07:24',
 '2026-08-05 00:07:30']
Length: 10, dtype: datetime64[us]

User_ID
[-4.32e+18 -3.28e+18 -4.62e+18  7.25e+18 -3.24e+18  8.08e+18 -3.07e+18
  5.93e+18 -9.08e+18  5.73e+18]

Round_Trip_Time_ms
[  nan 1123.   30.  476.  467.  413.  573.  626.  469.  527.]

IP_Address
<StringArray>
[    '10.0.65.171',    '194.87.207.6',   '81.167.144.58',   '170.39.78.152',
       '10.0.0.47', '209.236.123.126',  '80.202.228.214',   '170.39.78.177',
     '10.0.61.212',  '92.221.109.162']
Length: 10, dtype: str

Country_name
<StringArray>
['NO', 'AU', 'US', 'ID', 'BR', 'PL', 'IN', 'DK', 'DE', 'BD']
Length: 10, dtype: str

Region
<StringArray>
[                '-',          'Vestland',          'Virginia',
          'Rogaland',             'Viken', 'Troms og Finnmark',
       'Oslo County',         'East Java',             'Agder',
          'Nordland']
Length: 10, dtype: str

City
<StringArray>
[         '-',  'Urangsvag',    'Ashburn',    'Sandnes',   'Gressvik',
     'Klofta', 'Bjornevatn',       'Oslo',  'Haugesund',   'Surabaya']
Length: 10, dtype: str

Autonomous_System_Number_ASN
[ 29695  60117 393398 398986  15659  41164  29492  38778 197475 500034]

User_Agent_String
<StringArray>
[                                                                          'Mozilla/5.0  (iPhone; CPU iPhone OS 13_4 like Mac OS X) Gecko/20150101 Firefox/20.0.0.1618 (Chrome variation/248113',
                                           'Mozilla/5.0  (Linux; Android 4.1; Galaxy Nexus Build/JRN84D) AppleWebKit/537.36 (KHTML, like Gecko Chrome/46.0.2490.76 Mobile Safari/537.36 Browser',
                                                           'Mozilla/5.0  (iPad; CPU OS 7_1 like Mac OS X) AppleWebKit/533.1 (KHTML, like Gecko Version/4.0 Mobile Safari/533.1 variation/277457',
              'Mozilla/5.0  (Linux; Android 4.1; Galaxy Nexus Build/JRN84D) Build/OPS27.82-19-4; wv AppleWebKit/537.36 (KHTML, like Gecko Version/4.0 Chrome/85.0.4183.127 Mobile Safari/537.36',
                                       'Mozilla/5.0  (Linux; U; Android 2.2) Build/NMA26.42-169; wv AppleWebKit/537.36 (KHTML, like Gecko Version/4.0 Chrome/85.0.4183.120 Mobile Safari/537.36',
             'Mozilla/5.0  (Linux; Android 4.1; Galaxy Nexus Build/JRN84D) Build/NCQS26.69-64-5; wv AppleWebKit/537.36 (KHTML, like Gecko Version/4.0 Chrome/85.0.4183.127 Mobile Safari/537.36',
                                                  'Mozilla/5.066704189 Mozilla/5.0  (X11; CrOS x86_64 13020.67.3) AppleWebKit/537.36 (KHTML, like Gecko Chrome/69.0.3497.17.19.81 Safari/537.36',
                                            'Mozilla/5.0 (Linux; Android 10.0.99; H30-U10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.1931.96 Mobile Safari/537.36 variation/14113',
 'Mozilla/5.0 (Linux; U; Android 7.1.2; en-gb; Redmi 4A Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/12.6.5-go',
                                                                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.17.28.92 Safari/537.36']
Length: 10, dtype: str

Browser_Name_and_Version
<StringArray>
[            'Firefox 20.0.0.1618',         'Chrome Mobile 46.0.2490',
              'Android 2.3.3.2672', 'Chrome Mobile WebView 85.0.4183',
          'Chrome 69.0.3497.17.19',    'Chrome Mobile 81.0.4044.1931',
              'MiuiBrowser 12.6.5',          'Chrome 69.0.3497.17.28',
                'Chrome 86.0.4202',        'Chrome 79.0.3945.192.203']
Length: 10, dtype: str

OS_Name_and_Version
<StringArray>
[              'iOS 13.4',            'Android 4.1',                'iOS 7.1',
            'Android 2.2',   'Chrome OS 13020.67.3',        'Android 10.0.99',
          'Android 7.1.2',       'Mac OS X 10.14.6', 'Chromecast 1.36.159268',
  'Chrome OS 11316.123.0']
Length: 10, dtype: str

Device_Type
<StringArray>
['mobile', 'desktop', 'tablet', 'bot', 'unknown', nan]
Length: 6, dtype: str

Login_Successful
[False  True]

Is_Attack_IP
[False  True]

Is_Account_Takeover
[False]

In [34]:

# 5. Save the cleaned dataset
df.to_csv("cleaned_rba_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!